{
    "iit_colleges": [
        {
            "aiSummary": "A premier engineering institute in India, known for its academic excellence and research contributions. It offers a wide range of undergraduate and postgraduate programs, fostering innovation and leadership. The institute is located in Mumbai and is renowned for its vibrant campus life and strong industry connections.",
            "contactInfo": {
                "name": "Deputy Registrar (Academic)",
                "phone": "+91-22-25767987",
                "email": "adlingesd@iitb.ac.in",
                "address": "Powai, Mumbai 400076, Maharashtra, India"
            },
            "instituteCode": 102,
            "collegeType": "IIT",
            "collegeName": "Indian Institute of Technology Bombay",
            "state": "Maharashtra",
            "nirfRanking": 0,
            "courseName": "Industrial Engineering and Operations Research (4 Years, Bachelor of Technology)",
            "courseType": "B.Tech",
            "gender": "Gender-Neutral",
            "quota": "AI",
            "category": "OPEN",
            "openingRank": 1042,
            "closingRank": 1726,
            "profileImage": "https://placehold.co/300x300",
            "avgPkg": "0 LPA",
            "placementRating": 0,
            "collegeLifeRating": 0,
            "campusRating": 0,
            "year": 2024,
            "id": "2b6bb26a-c77f-11ef-b964-6a35931cdc08"
        },
        {
            "aiSummary": "A premier engineering institute in India, known for its academic excellence and research contributions. It offers a wide range of undergraduate and postgraduate programs, fostering innovation and leadership. The institute is located in Mumbai and is renowned for its vibrant campus life and strong industry connections.",
            "contactInfo": {
                "name": "Deputy Registrar (Academic)",
                "phone": "+91-22-25767987",
                "email": "adlingesd@iitb.ac.in",
                "address": "Powai, Mumbai 400076, Maharashtra, India"
            },
            "instituteCode": 102,
            "collegeType": "IIT",
            "collegeName": "Indian Institute of Technology Bombay",
            "state": "Maharashtra",
            "nirfRanking": 0,
            "courseName": "Chemical Engineering (4 Years, Bachelor of Technology)",
            "courseType": "B.Tech",
            "gender": "Gender-Neutral",
            "quota": "AI",
            "category": "OPEN",
            "openingRank": 650,
            "closingRank": 2545,
            "profileImage": "https://placehold.co/300x300",
            "avgPkg": "0 LPA",
            "placementRating": 0,
            "collegeLifeRating": 0,
            "campusRating": 0,
            "year": 2024,
            "id": "2b6a35fc-c77f-11ef-b964-6a35931cdc08"
        }
    ],
    "nit_colleges": [
        {
            "aiSummary": "Established in 1987, this institute is a premier engineering and technology institution in India, recognized as an Institute of National Importance. It offers a range of undergraduate, postgraduate, and doctoral programs. The campus provides excellent facilities, including hostels, sports amenities, and cultural events, fostering a vibrant student life.",
            "contactInfo": {
                "name": "Dr Mamta Khosla",
                "phone": "+91-9888604632",
                "email": "as.daug@nitj.ac.in",
                "address": "NIT Jalandhar - 144008, India"
            },
            "instituteCode": 201,
            "collegeType": "NIT",
            "collegeName": "Dr. B R Ambedkar National Institute of Technology, Jalandhar",
            "state": "Punjab",
            "nirfRanking": 0,
            "courseName": "Computer Science and Engineering (4 Years, Bachelor of Technology)",
            "courseType": "B.Tech",
            "gender": "Gender-Neutral",
            "quota": "OS",
            "category": "OPEN",
            "openingRank": 6330,
            "closingRank": 10957,
            "profileImage": "https://placehold.co/300x300",
            "avgPkg": "0 LPA",
            "placementRating": 0,
            "collegeLifeRating": 0,
            "campusRating": 0,
            "year": 2024,
            "id": "2b6a576c-c77f-11ef-b964-6a35931cdc08"
        },
        {
            "aiSummary": "Established in 1987, this institute is a premier engineering and technology institution in India, recognized as an Institute of National Importance. It offers a range of undergraduate, postgraduate, and doctoral programs. The campus provides excellent facilities, including hostels, sports amenities, and cultural events, fostering a vibrant student life.",
            "contactInfo": {
                "name": "Dr Mamta Khosla",
                "phone": "+91-9888604632",
                "email": "as.daug@nitj.ac.in",
                "address": "NIT Jalandhar - 144008, India"
            },
            "instituteCode": 201,
            "collegeType": "NIT",
            "collegeName": "Dr. B R Ambedkar National Institute of Technology, Jalandhar",
            "state": "Punjab",
            "nirfRanking": 0,
            "courseName": "Information Technology (4 Years, Bachelor of Technology)",
            "courseType": "B.Tech",
            "gender": "Gender-Neutral",
            "quota": "OS",
            "category": "OPEN",
            "openingRank": 10765,
            "closingRank": 14120,
            "profileImage": "https://placehold.co/300x300",
            "avgPkg": "0 LPA",
            "placementRating": 0,
            "collegeLifeRating": 0,
            "campusRating": 0,
            "year": 2024,
            "id": "2b6bdaf6-c77f-11ef-b964-6a35931cdc08"
        }
    ],
    "iiit_colleges": [
        {
            "aiSummary": "The institution, established under the Ministry of Education, offers B.Tech, M.Tech, and Ph.D. programs in various fields. It is recognized as an Institute of National Importance and ranks among the top IIITs in India. The campus provides modern facilities, including labs, libraries, and hostels, fostering a conducive learning environment.",
            "contactInfo": {
                "name": "Dr. Rusha Patra",
                "phone": "+91-03612801090",
                "email": "admissions@iiitg.ac.in",
                "address": "Bongora, Guwahati 781015"
            },
            "instituteCode": 303,
            "collegeType": "IIIT",
            "collegeName": "Indian Institute of Information Technology Guwahati",
            "state": "Assam",
            "nirfRanking": 0,
            "courseName": "Computer Science and Engineering (4 Years, Bachelor of Technology)",
            "courseType": "B.Tech",
            "gender": "Gender-Neutral",
            "quota": "AI",
            "category": "OPEN",
            "openingRank": 8898,
            "closingRank": 20821,
            "profileImage": "https://placehold.co/300x300",
            "avgPkg": "0 LPA",
            "placementRating": 0,
            "collegeLifeRating": 0,
            "campusRating": 0,
            "year": 2024,
            "id": "2b6af8d4-c77f-11ef-b964-6a35931cdc08"
        },
        {
            "aiSummary": "The institute is a premier Indian Institute of Information Technology located in Gwalior, Madhya Pradesh. It offers a range of undergraduate and integrated programs. Known for its strong industry connections, it collaborates with numerous top-tier companies, providing students with excellent placement opportunities.",
            "contactInfo": {
                "name": "Pankaj Gupta",
                "phone": "+91-751-2449720",
                "email": "pankaj@iiitm.ac.in",
                "address": "Morena Link Road, 474015, Gwalior, Madhya Pradesh"
            },
            "instituteCode": 301,
            "collegeType": "IIIT",
            "collegeName": "Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior",
            "state": "Madhya Pradesh",
            "nirfRanking": 0,
            "courseName": "Integrated B. Tech.(IT) and M. Tech (IT) (5 Years, Integrated B. Tech. and M. Tech.)",
            "courseType": "B.Tech + M.Tech",
            "gender": "Gender-Neutral",
            "quota": "AI",
            "category": "OPEN",
            "openingRank": 9708,
            "closingRank": 13577,
            "profileImage": "https://placehold.co/300x300",
            "avgPkg": "0 LPA",
            "placementRating": 0,
            "collegeLifeRating": 0,
            "campusRating": 0,
            "year": 2024,
            "id": "2b6817c2-c77f-11ef-b964-6a35931cdc08"
        }
    ],
    "gfti_colleges": [
        {
            "aiSummary": "Established in 1955 by B.M. Birla, this premier technical institute is a deemed university located in a sprawling 780-acre campus near Ranchi, Jharkhand. Known for its academic excellence, it offers a wide range of undergraduate, postgraduate, and doctoral programs, and boasts a vibrant student life with extensive facilities and strong industry connections.",
            "contactInfo": {
                "name": "Dr. Sudip Das",
                "phone": "+91-651-2275868",
                "email": "daac@bitmesra.ac.in",
                "address": "Birla Institute of Technology, Mesra, Ranchi - 835215, Jharkhand"
            },
            "instituteCode": 402,
            "collegeType": "GFTI",
            "collegeName": "Birla Institute of Technology, Mesra, Ranchi",
            "state": "Jharkhand",
            "nirfRanking": 0,
            "courseName": "Computer Science and Engineering (4 Years, Bachelor of Technology)",
            "courseType": "B.Tech",
            "gender": "Gender-Neutral",
            "quota": "AI",
            "category": "OPEN",
            "openingRank": 10209,
            "closingRank": 18030,
            "profileImage": "https://placehold.co/300x300",
            "avgPkg": "0 LPA",
            "placementRating": 0,
            "collegeLifeRating": 0,
            "campusRating": 0,
            "year": 2024,
            "id": "2b6ab19e-c77f-11ef-b964-6a35931cdc08"
        },
        {
            "aiSummary": "Located in Chandigarh, this esteemed institution has a rich history dating back to its roots in Lahore. It offers a robust academic curriculum similar to IITs, emphasizing industry engagement, research, and development. The campus spans 149 acres with modern facilities, fostering a conducive learning environment and vibrant student life.",
            "contactInfo": {
                "name": "Dr. Sanjay Batish",
                "phone": "+91-8699966880",
                "email": "admissions@pec.edu.in",
                "address": "Sector 12, Chandigarh 160012"
            },
            "instituteCode": 422,
            "collegeType": "GFTI",
            "collegeName": "Punjab Engineering College, Chandigarh",
            "state": "Chandigarh",
            "nirfRanking": 0,
            "courseName": "Computer Science Engineering (Artificial Intelligence) (4 Years, B. Tech / B. Tech (Hons.))",
            "courseType": "B.Tech",
            "gender": "Gender-Neutral",
            "quota": "OS",
            "category": "OPEN",
            "openingRank": 7865,
            "closingRank": 11603,
            "profileImage": "https://placehold.co/300x300",
            "avgPkg": "0 LPA",
            "placementRating": 0,
            "collegeLifeRating": 0,
            "campusRating": 0,
            "year": 2024,
            "id": "2b70c264-c77f-11ef-b964-6a35931cdc08"
        }
    ]
}